services:
  - type: web
    name: qwen3-coding-assistant
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python app.py
    plan: free
    envVars:
      - key: HF_HOME
        value: /opt/render/project/.cache/huggingface
